Adding in script for auto updating sui node version when theres a new…
SZNS/sui-node pull request #6
Opened 2024-08-01 18:27 UTC by davidyum

# Description

Whenever Sui releases a new version, we must update the full node with the release. Currently this process is manually done by sshing into the compute instance and restarting the sui full node and restarting the analytics indexer.

Linear Ticket: [(link to notion)](https://linear.app/szns-solutions/issue/SZN-181/automate-node-upgrades)

## Type of change

This PR adds a script that would automatically update the SUI version and restart the services. It also adds a cron job that would periodically poll the github releases and check for mainnet updates.

# How Has This Been Tested?

This was tested in the sui-node-test gcp account. I was able to run terraform apply and run the sui node in the test account and also checked that the new script and cron were successfully created

2024-08-02 16:59 UTC, d-szns commented on terraform/full-node/scripts/update_sui_node.sh
> +if [ "$ACTUAL_COMMIT_SHA" != "$CURRENT_VERSION" ]; then
Let me know if this adds complexity but would running `./sui-node -v` and comparing the tag version with the current binary version be better? I think ok to keep the sha in tmp space for now

2024-08-02 17:02 UTC, d-szns requested changes

2024-08-02 17:02 UTC, d-szns commented on terraform/full-node/scripts/update_sui_node.sh
> +    echo "A new mainnet release was found. Updating to $ACTUAL_COMMIT_SHA..."
Can we add the release/tag name too? Would be good to display as well so it's more descriptive than a hash

2024-08-02 17:02 UTC, d-szns commented on terraform/full-node/scripts/update_sui_node.sh
> +    wget -P $INSTALL_PATH "https://releases.sui.io/${ACTUAL_COMMIT_SHA}/sui-node"
```suggestion
    sudo wget -P $INSTALL_PATH "https://releases.sui.io/${ACTUAL_COMMIT_SHA}/sui-node"
```

Do we need sudo? I think the process is running as system so we might not need sudo in any of the commands here

2024-08-02 17:02 UTC, d-szns commented on terraform/full-node/scripts/update_sui_node.sh
> +    sudo systemctl restart sui-analytics-type-transaction-objects
We can remove this. Might be good as a separate job to update the analytics indexer. Nothing with the sui node upgrade is tightly coupled with the analytics service

2024-08-02 17:11 UTC, davidyum commented on terraform/full-node/scripts/update_sui_node.sh
> +if [ "$ACTUAL_COMMIT_SHA" != "$CURRENT_VERSION" ]; then
oh yeah it would make things much simpler if we can get the same value from just doing CURRENT_VERSION=$(/opt/sui/bin/sui-node -v) I will test to make sure that gives the same value

2024-08-02 17:14 UTC, davidyum commented on terraform/full-node/scripts/update_sui_node.sh
> +    sudo systemctl restart sui-analytics-type-transaction-objects
Ah gotcha I can remove the analytics indexer logic from here

2024-08-02 17:50 UTC, davidyum commented on terraform/full-node/scripts/update_sui_node.sh
> +if [ "$ACTUAL_COMMIT_SHA" != "$CURRENT_VERSION" ]; then
Ok so just checked and `sudo /opt/sui/bin/sui-node -V` gives back a value like `sui-node 1.29.2-09db80adf1af` I can probably just strip off the tag version 1.29.2 and compare those values

2024-08-02 17:55 UTC, davidyum commented on terraform/full-node/scripts/update_sui_node.sh
> +    wget -P $INSTALL_PATH "https://releases.sui.io/${ACTUAL_COMMIT_SHA}/sui-node"
yeah I think you are right we shouldn't need sudo

2024-08-05 14:38 UTC, d-szns approved these changes
lgtm

2024-08-05 14:47 UTC, davidyum commented
Gonna merge and will open up a new pr for the slack integration

2024-08-05 14:47 UTC, merged