add slack webhoook integration for notifications
SZNS/sui-node pull request #7
Opened 2024-08-05 18:28 UTC by davidyum

# Description

Whenever the script for SUI update runs we want to notify our team via slack. This PR adds slack notification to the webhook url specified in our secret manager.
Linear Ticket: [(link to notion)](https://linear.app/szns-solutions/issue/SZN-181/automate-node-upgrades)

## Type of change

This PR adds a new feature which would send a slack notification to the webhook url specified in our secret manager

# How Has This Been Tested?

This PR has been tested in our test environment. The script ran successfully and sent a message to our slack channel.

2024-08-06 16:49 UTC, d-szns requested changes

2024-08-06 16:49 UTC, d-szns commented on terraform/full-node/scripts/update_sui_node.sh
> +  SLACK_WEBHOOK_URL=$(gcloud secrets versions access latest --secret="slack-webhook-url" 2>/dev/null)
can we make `secret` reference a variable? Or make the slack messaging optional when deploying the terraform?

2024-08-07 15:12 UTC, davidyum commented on terraform/full-node/scripts/update_sui_node.sh
> +  SLACK_WEBHOOK_URL=$(gcloud secrets versions access latest --secret="slack-webhook-url" 2>/dev/null)
@d-szns created a variable SLACK_SECRET_NAME which can be set if its not set then the slack message will not send. If SLACK_SECRET_NAME is set then we will attempt to grab the value from secret manager and send the message to that channel

2024-08-07 17:29 UTC, d-szns approved these changes

2024-08-07 17:36 UTC, merged